[package]
name        = "howfastly-common"
description = "shared types, statistics, and parsing for howfastly"

edition.workspace    = true
license.workspace    = true
readme.workspace     = true
repository.workspace = true
version.workspace    = true

[dependencies]
serde.workspace = true

[dev-dependencies]
proptest.workspace   = true
serde_json.workspace = true
