[package]
name        = "howfastly"
description = "measure your connection speed to the fastly network"

edition.workspace    = true
license.workspace    = true
readme.workspace     = true
repository.workspace = true
version.workspace    = true

categories = ["command-line-utilities", "network-programming"]
keywords   = ["bandwidth", "fastly", "network", "speedtest"]

[dependencies]
anyhow.workspace     = true
clap.workspace       = true
common.workspace     = true
reqwest.workspace    = true
serde_json.workspace = true
tokio.workspace      = true
