[package]
name    = "howfastly-compute"
publish = false

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true

# the bin only builds for wasm32-wasip1, keep it out of host test builds
[[bin]]
name = "howfastly-compute"
path = "src/main.rs"
test = false

[dependencies]
fastly.workspace      = true
howfastly.workspace   = true
include_dir.workspace = true
serde_json.workspace  = true
