[build]
public_url = "/assets/"

# style.css is generated
# tailwind scans src/ and index.html on its own
[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = [
  "--input",
  "tailwind.css",
  "--output",
  "style.css",
  "--minify",
]
